# Netlify configuration for MITRE ACT website
# Increases memory allocation to prevent JavaScript heap out of memory errors

[build]
  command = "pnpm run generate"
  publish = "dist"
  environment = { NODE_OPTIONS = "--max-old-space-size=8192" }

# Note: Trailing slash handling is now done by generating directory structure
# with index.html files, which works on both GitHub Pages and Netlify
