# Netlify configuration for MITRE ACT website
# Increases memory allocation to prevent JavaScript heap out of memory errors

[build]
  command = "pnpm run build"
  publish = "dist"
  environment = { NODE_OPTIONS = "--max-old-space-size=8192" }

# Enable Netlify's Pretty URLs feature
# This automatically handles trailing slashes and .html extensions
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
